In [ ]:
# 년월일 칼럼을 하나 더 만들고 (check)
# 연도 날짜 지점 연월일 연월일 (check)
# 일시를 index로 변경, 연월일을 바이너리로 만들어서  (이건 merge해서 해야함)
# 각 feature의 경우의 수 구해서 모델돌리기 (약 100개정도?) 
# 이건 분류모델이니까 분류모델 반복문으로 다돌리고 
# 기후데이터를 가지고 경우의 수를 진행했다면 그다음에는 기후데이터의 feature을 뽑아서 돌려보렴....(기후데이터->기후데이터의feature)

# 분류모델 종류 - Logistic Regression,SGD,KNN,SVM,Decision Tree, Random Forest, LGBMClassifier
# 최적화 - lgbm ,smote(imbalanced), outlier제거, scaler
# 평가지표 - classification_report, f1_score, roc_auc_score(predic_proba)

In [ ]:
# from functools import reduce
# import pandas as pd
# dfs = [df1, df2, df3, dfN]
# df_merge = reduce(lambda left, right: pd.merge(left, right, on='name'), dfs)

# 출처: https://stopsilver.tistory.com/entry/python-pandas-여러개의-dataframe을-merge [언덕이 DIN의 신변잡기]

#이게머냐면 여러개 데이터 머지하는거

In [130]:
import pandas as pd 
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
import os
from functools import reduce
import warnings 
warnings.filterwarnings('ignore')

In [2]:
path = './preprocessed/'
os.listdir(path)

['df_coldwave.csv',
 'df_heatwave.csv',
 'df_troplical.csv',
 'preprocessed_고층기후데이터.csv',
 'preprocessed_주변국 기상데이터_199601to202108.csv',
 'preprocessed_주변국 기상데이터_중국 부분 제거.csv',
 '국내_바다.csv',
 '국내기후(백령도제외).csv']

In [3]:
df_coldwave = pd.read_csv('./preprocessed/df_coldwave.csv',encoding='cp949',index_col=0)
df_heatwave = pd.read_csv('./preprocessed/df_heatwave.csv',encoding='cp949',index_col=0)
df_tropical = pd.read_csv('./preprocessed/df_troplical.csv',encoding='cp949',index_col=0)
df_high = pd.read_csv('./preprocessed/preprocessed_고층기후데이터.csv',index_col=0)
df_near = pd.read_csv('./preprocessed/preprocessed_주변국 기상데이터_199601to202108.csv',index_col=0)
df_near_nochi = pd.read_csv('./preprocessed/preprocessed_주변국 기상데이터_중국 부분 제거.csv',index_col=0)
df_sea = pd.read_csv('./preprocessed/국내_바다.csv',index_col=0)
df_korea = pd.read_csv('./preprocessed/국내기후(백령도제외).csv',index_col=0)

In [ ]:
# 모든피쳐 다떄려넣고 각 재난마다 모델 돌려보기 
# 처음엔 한파 
# 일단 모델 하나라도 돌려보는게 목표야 시간이 너무 오래걸리니까 하나씩 조합을 해보자 씨발
# 기후데이터 크기 줄여야돼!!!!

In [ ]:
# 재난데이터 쓸모없는 column 버리기
# 인덱스 리셋해주기
# 재난데이터 날짜 중복값 제거해주기

In [7]:
df_coldwave.drop(['연도','날짜','지점'],axis=1,inplace=True)
# df_heatwave.drop(['연도','날짜','지점'],axis=1,inplace=True)
# df_tropical.drop(['연도','날짜','지점'],axis=1,inplace=True)

In [5]:
df_tropical.reset_index(inplace=True)

In [11]:
df_coldwave = df_coldwave.drop_duplicates()

In [ ]:
# 한파랑 고층기후데이터조합

In [111]:
cold_high = pd.merge(df_coldwave,df_high, how='right',on='일시')

In [84]:
cold_high.iloc[0:30]

,일시,재난일어난날,50hPa_고도,50hPa_기온,50hPa_이슬점,50hPa_풍향,50hPa_풍속,70hPa_고도,70hPa_기온,70hPa_이슬점,...,925hPa_고도,925hPa_기온,925hPa_이슬점,925hPa_풍향,925hPa_풍속,1000hPa_고도,1000hPa_기온,1000hPa_이슬점,1000hPa_풍향,1000hPa_풍속
0,1990-01-01,1,20332.50,-55.350,-76.064706,253.750,29.500,18182.50,-53.700,-78.023153,...,780.810561,8.615578,0.716938,230.239795,12.991223,183.50,-2.750,-9.500,255.00,6.250000
1,1990-01-02,1,20355.00,-57.200,-76.064706,275.000,32.500,18222.50,-55.100,-78.023153,...,780.810561,8.615578,0.716938,230.239795,12.991223,194.50,-4.650,-11.525,337.50,6.500000
2,1990-01-03,1,20370.00,-55.600,-76.064706,268.750,32.500,18237.50,-58.100,-78.023153,...,780.810561,8.615578,0.716938,230.239795,12.991223,206.00,-5.600,-13.850,150.00,7.250000
3,1990-01-04,1,20377.50,-56.450,-76.064706,242.500,24.250,18255.00,-59.650,-78.023153,...,780.810561,8.615578,0.716938,230.239795,12.991223,209.75,-2.700,-12.200,228.75,6.500000
4,1990-01-05,0,20352.50,-58.225,-76.064706,248.750,32.625,18237.50,-57.100,-78.023153,...,780.810561,8.615578,0.716938,230.239795,12.991223,177.25,-0.850,-7.325,232.50,6.000000
5,1990-01-06,1,20412.50,-58.000,-76.064706,262.500,26.750,18302.50,-59.400,-78.023153,...,780.810561,8.615578,0.716938,230.239795,12.991223,229.50,-4.700,-15.200,236.25,9.000000
6,1990-01-07,1,20507.50,-59.250,-76.064706,256.250,16.250,18402.50,-59.200,-78.023153,...,780.810561,8.615578,0.716938,230.239795,12.991223,257.25,-2.950,-13.450,76.25,7.500000
7,1990-01-08,1,20425.00,-56.700,-76.064706,243.125,25.250,18295.00,-58.500,-78.023153,...,780.810561,8.615578,0.716938,230.239795,12.991223,232.25,2.275,-9.475,118.75,6.500000
8,1990-01-09,0,20411.25,-54.775,-76.064706,263.750,30.875,18276.25,-58.125,-78.023153,...,780.810561,8.615578,0.716938,230.239795,12.991223,142.25,5.500,-0.175,76.25,5.500000
9,1990-01-10,0,20432.50,-53.550,-76.064706,245.000,36.750,18295.00,-57.600,-78.023153,...,780.810561,8.615578,0.716938,230.239795,12.991223,138.50,2.650,-2.200,291.25,8.250000
10,1990-01-11,0,20400.00,-54.650,-76.064706,252.500,33.000,18255.00,-57.800,-78.023153,...,780.810561,8.615578,0.716938,230.239795,12.991223,198.50,1.950,-4.550,252.50,4.750000
11,1990-01-12,0,20375.00,-57.150,-76.064706,250.000,45.750,18215.00,-54.050,-78.023153,...,780.810561,-6.300000,-12.250000,230.239795,12.991223,183.50,-1.350,-9.350,302.50,7.500000
12,1990-01-13,0,20330.00,-56.050,-76.064706,257.500,42.500,18200.00,-56.600,-78.023153,...,780.810561,-10.087500,-22.593750,230.239795,12.991223,204.00,-6.100,-19.600,297.50,8.500000
13,1990-01-14,1,20387.50,-57.700,-76.064706,260.000,30.000,18272.50,-57.350,-78.023153,...,780.810561,-10.125000,-23.687500,230.239795,12.991223,207.50,-3.800,-9.675,308.75,6.500000
14,1990-01-15,0,20443.75,-55.675,-76.064706,229.375,21.500,18313.75,-58.375,-78.023153,...,780.810561,-9.791667,-23.854167,230.239795,12.991223,191.75,-4.950,-12.800,228.75,4.750000
15,1990-01-16,1,20407.50,-53.400,-76.064706,255.000,31.500,18280.00,-59.150,-78.023153,...,780.810561,-9.458333,-24.020833,230.239795,12.991223,176.50,-3.250,-12.250,245.00,5.500000
16,1990-01-17,1,20412.50,-55.100,-76.064706,260.000,34.500,18272.50,-58.000,-78.023153,...,780.810561,-9.125000,-24.187500,230.239795,12.991223,163.25,-2.050,-11.550,146.25,5.250000
17,1990-01-18,0,20440.00,-57.200,-76.064706,252.500,37.250,18317.50,-59.050,-78.023153,...,780.810561,-8.791667,-24.354167,230.239795,12.991223,162.50,0.100,-8.625,312.50,11.250000
18,1990-01-19,0,20465.00,-55.675,-76.064706,234.375,17.750,18333.75,-58.025,-78.023153,...,780.810561,-8.480739,-24.390998,230.239795,12.991223,230.75,-7.400,-18.150,307.50,10.750000
19,1990-01-20,1,20402.50,-54.400,-76.064706,226.250,13.875,18392.50,-57.000,-78.023153,...,780.810561,-8.259434,-23.908491,230.239795,12.991223,248.00,-8.050,-18.800,231.25,6.000000
20,1990-01-21,1,20355.00,-53.850,-76.064706,240.000,33.000,18205.00,-55.400,-78.023153,...,780.810561,-8.045597,-23.382704,230.239795,12.991223,216.00,-3.500,-9.425,236.25,7.250000
21,1990-01-22,1,20338.75,-57.025,-76.064706,261.250,33.000,18202.50,-53.450,-78.023153,...,780.810561,-7.831761,-22.856918,230.239795,12.991223,231.75,-11.950,-21.950,303.75,13.250000
22,1990-01-23,1,20327.50,-56.800,-76.064706,250.000,33.250,18182.50,-56.050,-78.023153,...,780.810561,-7.617925,-22.331132,230.239795,12.991223,207.25,-12.700,-22.450,295.00,8.500000
23,1990-01-24,1,20320.00,-57.350,-76.064706,230.625,44.750,18185.00,-54.825,-78.023153,...,780.810561,-7.404088,-21.805346,230.239795,12.991223,176.75,-15.050,-24.550,246.25,10.500000
24,1990-01-25,1,20357.50,-57.800,-76.064706,253.125,39.625,18240.00,-55.750,-78.023153,...,780.810561,-7.190252,-21.279560,230.239795,12.991223,279.00,-15.500,-26.250,238.75,6.388023
25,1990-01-26,1,20387.50,-56.725,-76.064706,248.125,40.375,18257.50,-57.300,-78.023153,...,780.810561,-6.976415,-20.753774,230.239795,12.991223,289.25,-10.800,-23.050,161.25,7.000000
26,1990-01-27,1,20402.50,-56.700,-76.064706,261.250,37.250,18272.50,-57.000,-78.023153,...,780.810561,-6.762579,-20.227987,230.239795,12.991223,278.00,-4.700,-14.450,61.25,7.500000
27,1990-01-28,1,20438.75,-58.725,-76.064706,251.250,47.750,18335.00,-60.750,-78.023153,...,780.810561,-6.548742,-19.702201,230.239795,12.991223,223.75,-0.825,-7.500,148.75,11.000000
28,1990-01-29,0,20393.75,-58.625,-76.064706,263.750,45.375,18310.00,-64.050,-78.023153,...,780.810561,-6.334906,-19.176415,230.239795,12.991223,187.00,1.325,-1.775,222.50,5.750000
29,1990-01-30,0,20372.50,-59.100,-76.064706,261.250,40.125,18280.00,-63.100,-78.023153,...,780.810561,-6.121069,-18.650629,230.239795,12.991223,210.00,-0.950,-3.075,85.00,7.000000

In [112]:
# 재난일어난날을 바이너리로 만들어주기 
cold_high['재난일어난날'] = cold_high['재난일어난날'].fillna(0)

In [113]:
cold_high['재난일어난날'] =cold_high['재난일어난날'].apply(lambda x: x if str(x) == '0' else '1')

In [87]:
cold_high.tail()

,일시,재난일어난날,50hPa_고도,50hPa_기온,50hPa_이슬점,50hPa_풍향,50hPa_풍속,70hPa_고도,70hPa_기온,70hPa_이슬점,...,925hPa_고도,925hPa_기온,925hPa_이슬점,925hPa_풍향,925hPa_풍속,1000hPa_고도,1000hPa_기온,1000hPa_이슬점,1000hPa_풍향,1000hPa_풍속
11683,2021-12-27,1,20457.5,-58.450,-89.200,270.000,37.000,18337.50,-56.250,-87.75,...,852.00,-7.50,-10.850,293.75,26.00,243.75,-6.150,-11.050,220.00,3.50
11684,2021-12-28,1,20442.5,-59.350,-89.850,277.500,48.250,18325.00,-57.750,-88.50,...,837.00,-3.05,-6.200,257.50,17.00,215.25,-0.850,-4.725,161.25,6.00
11685,2021-12-29,0,20485.0,-58.025,-89.025,241.875,30.625,18333.75,-58.000,-89.00,...,789.25,-3.45,-6.825,272.50,25.00,167.00,0.825,-4.800,266.25,14.75
11686,2021-12-30,0,20480.0,-59.625,-89.875,228.125,32.125,18332.50,-54.725,-86.35,...,821.25,-9.90,-17.550,312.50,21.25,213.75,-4.550,-14.550,307.50,14.00
11687,2021-12-31,1,20462.5,-58.700,-86.450,277.500,29.500,18350.00,-59.800,-86.80,...,856.50,-12.25,-23.750,316.25,19.25,256.25,-7.750,-21.000,313.75,11.75

In [86]:
# 날짜맞추기위해 행을삭제하고 쓸모없는 column 제거 하기 
cold_high.isnull().sum().sum()

0

In [63]:
# 고층기후 1990-01-01 부터 2021-12-31 까지
# 한파 1973-02-03 부터 2022-02-24 까지
# 한파와 고층기후의 null값이 0이기때문에 날짜를 맞추기위해 dropna를해줌 (이거 머지를 고층기후로 했기때문에 필요없음)

In [114]:
# 재난이 일어난 시기를 2주 밀어서 예측시도
cold_high['재난일어난날'] = cold_high['재난일어난날'].shift(periods=14, axis=0)

In [115]:
# 밀어난 시기만큼 nan값이 생겼으니 그 시기를 제거
cold_high.dropna(inplace=True)

In [94]:
cold_high

,일시,재난일어난날,50hPa_고도,50hPa_기온,50hPa_이슬점,50hPa_풍향,50hPa_풍속,70hPa_고도,70hPa_기온,70hPa_이슬점,...,925hPa_고도,925hPa_기온,925hPa_이슬점,925hPa_풍향,925hPa_풍속,1000hPa_고도,1000hPa_기온,1000hPa_이슬점,1000hPa_풍향,1000hPa_풍속
14,1990-01-15,1,20443.75,-55.675,-76.064706,229.375,21.500,18313.75,-58.375,-78.023153,...,780.810561,-9.791667,-23.854167,230.239795,12.991223,191.75,-4.950,-12.800,228.75,4.75
15,1990-01-16,1,20407.50,-53.400,-76.064706,255.000,31.500,18280.00,-59.150,-78.023153,...,780.810561,-9.458333,-24.020833,230.239795,12.991223,176.50,-3.250,-12.250,245.00,5.50
16,1990-01-17,1,20412.50,-55.100,-76.064706,260.000,34.500,18272.50,-58.000,-78.023153,...,780.810561,-9.125000,-24.187500,230.239795,12.991223,163.25,-2.050,-11.550,146.25,5.25
17,1990-01-18,1,20440.00,-57.200,-76.064706,252.500,37.250,18317.50,-59.050,-78.023153,...,780.810561,-8.791667,-24.354167,230.239795,12.991223,162.50,0.100,-8.625,312.50,11.25
18,1990-01-19,0,20465.00,-55.675,-76.064706,234.375,17.750,18333.75,-58.025,-78.023153,...,780.810561,-8.480739,-24.390998,230.239795,12.991223,230.75,-7.400,-18.150,307.50,10.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11683,2021-12-27,0,20457.50,-58.450,-89.200000,270.000,37.000,18337.50,-56.250,-87.750000,...,852.000000,-7.500000,-10.850000,293.750000,26.000000,243.75,-6.150,-11.050,220.00,3.50
11684,2021-12-28,0,20442.50,-59.350,-89.850000,277.500,48.250,18325.00,-57.750,-88.500000,...,837.000000,-3.050000,-6.200000,257.500000,17.000000,215.25,-0.850,-4.725,161.25,6.00
11685,2021-12-29,0,20485.00,-58.025,-89.025000,241.875,30.625,18333.75,-58.000,-89.000000,...,789.250000,-3.450000,-6.825000,272.500000,25.000000,167.00,0.825,-4.800,266.25,14.75
11686,2021-12-30,0,20480.00,-59.625,-89.875000,228.125,32.125,18332.50,-54.725,-86.350000,...,821.250000,-9.900000,-17.550000,312.500000,21.250000,213.75,-4.550,-14.550,307.50,14.00
11687,2021-12-31,0,20462.50,-58.700,-86.450000,277.500,29.500,18350.00,-59.800,-86.800000,...,856.500000,-12.250000,-23.750000,316.250000,19.250000,256.25,-7.750,-21.000,313.75,11.75

In [ ]:
# 이제 오브젝트 타입을 뉴메릭으로 만들어주기..

In [ ]:
# cold_high['일시'] = cold_high['일시'].apply(lambda x: x.replace('-',''))
# object일시를 바꿔줘도ㅗ되지만 어차피 ! 피쳐에안들어가. 그러니까 그냥 없애도돼 
cold_high = cold_high.drop('일시',axis=1)

In [122]:
#굳이 어플라이쓸필요없었..ㅠㅠ 
cold_high['재난일어난날'] = cold_high['재난일어난날'].astype(int)

In [123]:
cold_high.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11674 entries, 14 to 11687
Data columns (total 66 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   재난일어난날       11674 non-null  int32
 1   50hPa_고도     11674 non-null  float64
 2   50hPa_기온     11674 non-null  float64
 3   50hPa_이슬점    11674 non-null  float64
 4   50hPa_풍향     11674 non-null  float64
 5   50hPa_풍속     11674 non-null  float64
 6   70hPa_고도     11674 non-null  float64
 7   70hPa_기온     11674 non-null  float64
 8   70hPa_이슬점    11674 non-null  float64
 9   70hPa_풍향     11674 non-null  float64
 10  70hPa_풍속     11674 non-null  float64
 11  100hPa_고도    11674 non-null  float64
 12  100hPa_기온    11674 non-null  float64
 13  100hPa_이슬점   11674 non-null  float64
 14  100hPa_풍향    11674 non-null  float64
 15  100hPa_풍속    11674 non-null  float64
 16  150hPa_고도    11674 non-null  float64
 17  150hPa_기온    11674 non-null  float64
 18  150hPa_이슬점   11674 non-null  float64
 19  150hPa_풍향    11674 non-null  float64
 20  150hPa_풍속    11674 non-null  float64
 21  200hPa_고도    11674 non-null  float64
 22  200hPa_기온    11674 non-null  float64
 23  200hPa_이슬점   11674 non-null  float64
 24  200hPa_풍향    11674 non-null  float64
 25  200hPa_풍속    11674 non-null  float64
 26  250hPa_고도    11674 non-null  float64
 27  250hPa_기온    11674 non-null  float64
 28  250hPa_이슬점   11674 non-null  float64
 29  250hPa_풍향    11674 non-null  float64
 30  250hPa_풍속    11674 non-null  float64
 31  300hPa_고도    11674 non-null  float64
 32  300hPa_기온    11674 non-null  float64
 33  300hPa_이슬점   11674 non-null  float64
 34  300hPa_풍향    11674 non-null  float64
 35  300hPa_풍속    11674 non-null  float64
 36  400hPa_고도    11674 non-null  float64
 37  400hPa_기온    11674 non-null  float64
 38  400hPa_이슬점   11674 non-null  float64
 39  400hPa_풍향    11674 non-null  float64
 40  400hPa_풍속    11674 non-null  float64
 41  500hPa_고도    11674 non-null  float64
 42  500hPa_기온    11674 non-null  float64
 43  500hPa_이슬점   11674 non-null  float64
 44  500hPa_풍향    11674 non-null  float64
 45  500hPa_풍속    11674 non-null  float64
 46  700hPa_고도    11674 non-null  float64
 47  700hPa_기온    11674 non-null  float64
 48  700hPa_이슬점   11674 non-null  float64
 49  700hPa_풍향    11674 non-null  float64
 50  700hPa_풍속    11674 non-null  float64
 51  850hPa_고도    11674 non-null  float64
 52  850hPa_기온    11674 non-null  float64
 53  850hPa_이슬점   11674 non-null  float64
 54  850hPa_풍향    11674 non-null  float64
 55  850hPa_풍속    11674 non-null  float64
 56  925hPa_고도    11674 non-null  float64
 57  925hPa_기온    11674 non-null  float64
 58  925hPa_이슬점   11674 non-null  float64
 59  925hPa_풍향    11674 non-null  float64
 60  925hPa_풍속    11674 non-null  float64
 61  1000hPa_고도   11674 non-null  float64
 62  1000hPa_기온   11674 non-null  float64
 63  1000hPa_이슬점  11674 non-null  float64
 64  1000hPa_풍향   11674 non-null  float64
 65  1000hPa_풍속   11674 non-null  float64
dtypes: float64(65), int32(1)
memory usage: 5.9 MB

In [ ]:
# 여기까지 한파와고층기후 전처리 끗

In [ ]:
# 모델링 해보기

In [127]:
cold_high.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11674 entries, 14 to 11687
Data columns (total 66 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   재난일어난날       11674 non-null  int32
 1   50hPa_고도     11674 non-null  float64
 2   50hPa_기온     11674 non-null  float64
 3   50hPa_이슬점    11674 non-null  float64
 4   50hPa_풍향     11674 non-null  float64
 5   50hPa_풍속     11674 non-null  float64
 6   70hPa_고도     11674 non-null  float64
 7   70hPa_기온     11674 non-null  float64
 8   70hPa_이슬점    11674 non-null  float64
 9   70hPa_풍향     11674 non-null  float64
 10  70hPa_풍속     11674 non-null  float64
 11  100hPa_고도    11674 non-null  float64
 12  100hPa_기온    11674 non-null  float64
 13  100hPa_이슬점   11674 non-null  float64
 14  100hPa_풍향    11674 non-null  float64
 15  100hPa_풍속    11674 non-null  float64
 16  150hPa_고도    11674 non-null  float64
 17  150hPa_기온    11674 non-null  float64
 18  150hPa_이슬점   11674 non-null  float64
 19  150hPa_풍향    11674 non-null  float64
 20  150hPa_풍속    11674 non-null  float64
 21  200hPa_고도    11674 non-null  float64
 22  200hPa_기온    11674 non-null  float64
 23  200hPa_이슬점   11674 non-null  float64
 24  200hPa_풍향    11674 non-null  float64
 25  200hPa_풍속    11674 non-null  float64
 26  250hPa_고도    11674 non-null  float64
 27  250hPa_기온    11674 non-null  float64
 28  250hPa_이슬점   11674 non-null  float64
 29  250hPa_풍향    11674 non-null  float64
 30  250hPa_풍속    11674 non-null  float64
 31  300hPa_고도    11674 non-null  float64
 32  300hPa_기온    11674 non-null  float64
 33  300hPa_이슬점   11674 non-null  float64
 34  300hPa_풍향    11674 non-null  float64
 35  300hPa_풍속    11674 non-null  float64
 36  400hPa_고도    11674 non-null  float64
 37  400hPa_기온    11674 non-null  float64
 38  400hPa_이슬점   11674 non-null  float64
 39  400hPa_풍향    11674 non-null  float64
 40  400hPa_풍속    11674 non-null  float64
 41  500hPa_고도    11674 non-null  float64
 42  500hPa_기온    11674 non-null  float64
 43  500hPa_이슬점   11674 non-null  float64
 44  500hPa_풍향    11674 non-null  float64
 45  500hPa_풍속    11674 non-null  float64
 46  700hPa_고도    11674 non-null  float64
 47  700hPa_기온    11674 non-null  float64
 48  700hPa_이슬점   11674 non-null  float64
 49  700hPa_풍향    11674 non-null  float64
 50  700hPa_풍속    11674 non-null  float64
 51  850hPa_고도    11674 non-null  float64
 52  850hPa_기온    11674 non-null  float64
 53  850hPa_이슬점   11674 non-null  float64
 54  850hPa_풍향    11674 non-null  float64
 55  850hPa_풍속    11674 non-null  float64
 56  925hPa_고도    11674 non-null  float64
 57  925hPa_기온    11674 non-null  float64
 58  925hPa_이슬점   11674 non-null  float64
 59  925hPa_풍향    11674 non-null  float64
 60  925hPa_풍속    11674 non-null  float64
 61  1000hPa_고도   11674 non-null  float64
 62  1000hPa_기온   11674 non-null  float64
 63  1000hPa_이슬점  11674 non-null  float64
 64  1000hPa_풍향   11674 non-null  float64
 65  1000hPa_풍속   11674 non-null  float64
dtypes: float64(65), int32(1)
memory usage: 5.9 MB

In [129]:
y = cold_high.재난일어난날
x = cold_high.drop('재난일어난날',axis=1)

In [131]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [135]:
# 분류모델 import 
# Logistic Regression,SGD,KNN,SVM,Decision Tree, Random Forest, LGBMClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report,roc_auc_score,f1_score

lr = LogisticRegression()
knn = KNeighborsClassifier()
svm = SVC()
dtc = DecisionTreeClassifier()
rfc = RandomForestClassifier()
lgbm = LGBMClassifier()

In [140]:
models = [lr,knn,dtc,rfc,lgbm]
# result = []
for i in models:
    i.fit(x_train,y_train)
    pred = i.predict(x_test)
    proba = i.predict_proba(x_test)[:,1]
    
    print(i.__class__.__name__)
    print('f1_score :', f1_score(y_test,pred))
    print('roc_auc_score :',roc_auc_score(y_test,proba))
    print('-'*50)

LogisticRegression
f1_score : 0.2717948717948718
roc_auc_score : 0.902566236085602
--------------------------------------------------
KNeighborsClassifier
f1_score : 0.3275862068965517
roc_auc_score : 0.8314763890721029
--------------------------------------------------
DecisionTreeClassifier
f1_score : 0.3883161512027492
roc_auc_score : 0.6515134603090847
--------------------------------------------------
RandomForestClassifier
f1_score : 0.2680412371134021
roc_auc_score : 0.9080347509022584
--------------------------------------------------
LGBMClassifier
f1_score : 0.36888888888888893
roc_auc_score : 0.907758238710354
--------------------------------------------------

In [ ]:
#f1 score가 너무 낮게나왔으니 임밸런스 데이터를 제거하고 다시

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
scaler.fit(x_train)

In [145]:
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

StandardScaler()

In [142]:
import imblearn
from imblearn.over_sampling import SMOTE

In [146]:
smote = SMOTE(random_state=0)
x_train_sm,y_train_sm = smote.fit_resample(x_train_scaled,y_train)

In [148]:
y_train_sm.value_counts()

0    8258
1    8258
Name: 재난일어난날, dtype: int64

In [151]:
models = [lr,knn,dtc,rfc,lgbm]
# result = []
for i in models:
    i.fit(x_train_sm,y_train_sm)
    pred = i.predict(x_test_scaled)
    proba = i.predict_proba(x_test_scaled)[:,1]
    
    print(i.__class__.__name__)
    print(classification_report(y_test,pred))
    print('roc_auc_score :',roc_auc_score(y_test,proba))
    print('-'*50)

LogisticRegression
              precision    recall  f1-score   support

           0       0.98      0.82      0.89      2046
           1       0.41      0.89      0.56       289

    accuracy                           0.83      2335
   macro avg       0.70      0.85      0.73      2335
weighted avg       0.91      0.83      0.85      2335

f1_score : 0.5601750547045953
roc_auc_score : 0.9125426606730324
--------------------------------------------------
KNeighborsClassifier
              precision    recall  f1-score   support

           0       0.98      0.78      0.87      2046
           1       0.36      0.88      0.51       289

    accuracy                           0.79      2335
   macro avg       0.67      0.83      0.69      2335
weighted avg       0.90      0.79      0.82      2335

f1_score : 0.5079681274900398
roc_auc_score : 0.8700164385229683
--------------------------------------------------
DecisionTreeClassifier
              precision    recall  f1-score   support

           0       0.94      0.88      0.91      2046
           1       0.41      0.58      0.48       289

    accuracy                           0.84      2335
   macro avg       0.67      0.73      0.69      2335
weighted avg       0.87      0.84      0.86      2335

f1_score : 0.47851002865329506
roc_auc_score : 0.7297875506939019
--------------------------------------------------
RandomForestClassifier
              precision    recall  f1-score   support

           0       0.95      0.89      0.92      2046
           1       0.45      0.66      0.53       289

    accuracy                           0.86      2335
   macro avg       0.70      0.77      0.73      2335
weighted avg       0.89      0.86      0.87      2335

f1_score : 0.5342657342657343
roc_auc_score : 0.906988739950008
--------------------------------------------------
LGBMClassifier
              precision    recall  f1-score   support

           0       0.94      0.90      0.92      2046
           1       0.45      0.59      0.51       289

    accuracy                           0.86      2335
   macro avg       0.70      0.74      0.72      2335
weighted avg       0.88      0.86      0.87      2335

f1_score : 0.5112781954887219
roc_auc_score : 0.9051892966950451
--------------------------------------------------

In [152]:
# 한파와 주변국 조합

In [181]:
df_coldwave

               일시      재난일어난날
0      1973-01-03  1973-01-03
16     1973-01-04  1973-01-04
18     1973-01-06  1973-01-06
19     1973-01-11  1973-01-11
22     1973-01-12  1973-01-12
...           ...         ...
21950  2022-02-20  2022-02-20
21952  2022-02-21  2022-02-21
21960  2022-02-22  2022-02-22
21963  2022-02-23  2022-02-23
21972  2022-02-24  2022-02-24

[2270 rows x 2 columns]

In [180]:
df_near

,도시명,일시,평균기온,최고기온,최저기온,습도,풍향,풍속,강수량,해면기압,이슬점 온도,군집
0,청진,1996-01-01,-5.528571,-0.1,-9.9,53.571429,330.0,0.571429,0.0,1018.685714,-13.657143,n2
1,청진,1996-01-02,-3.825000,1.3,-8.2,72.875000,80.0,0.500000,0.0,1014.037500,-8.025000,n2
2,청진,1996-01-03,-6.912500,-1.4,-11.7,48.375000,330.0,3.000000,0.0,1010.537500,-16.100000,n2
3,청진,1996-01-04,-9.475000,-3.4,-19.2,56.500000,320.0,0.250000,0.0,1020.800000,-16.625000,n2
4,청진,1996-01-05,-4.487500,0.5,-9.9,71.750000,290.0,0.375000,0.0,1021.800000,-8.837500,n2
...,...,...,...,...,...,...,...,...,...,...,...,...
9370,후쿠오카,2021-08-27,29.175000,32.8,25.6,70.495833,30.0,5.125000,0.0,1014.391667,23.162500,n5
9371,후쿠오카,2021-08-28,28.641667,32.3,25.1,72.362500,40.0,4.958333,0.0,1014.325000,23.000000,n5
9372,후쿠오카,2021-08-29,28.908333,32.4,25.5,72.687500,290.0,5.041667,0.0,1014.754167,23.375000,n5
9373,후쿠오카,2021-08-30,28.904167,32.5,25.8,75.795833,310.0,4.541667,0.0,1015.587500,24.112500,n5
9374,후쿠오카,2021-08-31,29.100000,32.3,26.8,73.162500,290.0,4.875000,0.0,1013.795833,23.754167,n5

In [155]:
cold_near = pd.merge(df_coldwave,df_near, how='right',on='일시')

In [157]:
cold_near

,일시,재난일어난날,도시명,평균기온,최고기온,최저기온,습도,풍향,풍속,강수량,해면기압,이슬점 온도,군집
0,1996-01-01,1996-01-01,청진,-5.528571,-0.1,-9.9,53.571429,330.0,0.571429,0.0,1018.685714,-13.657143,n2
1,1996-01-02,1996-01-02,청진,-3.825000,1.3,-8.2,72.875000,80.0,0.500000,0.0,1014.037500,-8.025000,n2
2,1996-01-03,NaN,청진,-6.912500,-1.4,-11.7,48.375000,330.0,3.000000,0.0,1010.537500,-16.100000,n2
3,1996-01-04,1996-01-04,청진,-9.475000,-3.4,-19.2,56.500000,320.0,0.250000,0.0,1020.800000,-16.625000,n2
4,1996-01-05,1996-01-05,청진,-4.487500,0.5,-9.9,71.750000,290.0,0.375000,0.0,1021.800000,-8.837500,n2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
271870,2021-08-27,NaN,후쿠오카,29.175000,32.8,25.6,70.495833,30.0,5.125000,0.0,1014.391667,23.162500,n5
271871,2021-08-28,NaN,후쿠오카,28.641667,32.3,25.1,72.362500,40.0,4.958333,0.0,1014.325000,23.000000,n5
271872,2021-08-29,NaN,후쿠오카,28.908333,32.4,25.5,72.687500,290.0,5.041667,0.0,1014.754167,23.375000,n5
271873,2021-08-30,NaN,후쿠오카,28.904167,32.5,25.8,75.795833,310.0,4.541667,0.0,1015.587500,24.112500,n5
271874,2021-08-31,NaN,후쿠오카,29.100000,32.3,26.8,73.162500,290.0,4.875000,0.0,1013.795833,23.754167,n5

In [158]:
cold_near['재난일어난날'] = cold_near['재난일어난날'].fillna(0)

In [160]:
cold_near['재난일어난날'] =cold_near['재난일어난날'].apply(lambda x: x if str(x) == '0' else '1')

In [164]:
# 쓸모없는 column 제거
cold_near.drop('일시',axis=1,inplace=True)

In [167]:
# 전부 뉴메릭으로 만들기 
cold_near['재난일어난날']=cold_near['재난일어난날'].astype(int)

In [ ]:
cold_near = pd.get_dummies(cold_near)

In [175]:
# 재난일어난날 2주뒤로 미뤄서 예측값 찾기 
cold_near['재난일어난날'] = cold_near['재난일어난날'].shift(periods=14, axis=0)

In [178]:
cold_near.dropna(inplace=True)

In [ ]:
# 한파 주변국 전처리 완료..

In [ ]:
# 한파 주변국 조합으로 모델 돌려보기

In [ ]:
models = [lr,knn,dtc,rfc,lgbm]
# result = []
for i in models:
    i.fit(x_train,y_train)
    pred = i.predict(x_test)
    proba = i.predict_proba(x_test)[:,1]
    
    print(i.__class__.__name__)
    print('f1_score :', f1_score(y_test,pred))
    print('roc_auc_score :',roc_auc_score(y_test,proba))
    print('-'*50)