In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/국내기후(백령도제외).csv',index_col=0)
df.tail()

,시간,관측지점,평균 기온,최저 기온,최고 기온,1시간 최다강수량,일강수량,최대 순간풍속,최대 순간 풍속 풍향,최대 풍속,...,합계 일사,일 최심신적설,일 최심적설,합계 3시간 신적설,평균 전운량,평균 중하층운량,평균 지면온도,합계 대형증발량,합계 소형증발량,안개 계속 시간
11683,2021-12-27,제주,4.1,0.8,6.5,0.0,0.1,12.8,20.0,6.8,...,1.37,0.5,1.2,0.5,8.1,8.1,3.9,1.0,1.4,0.0
11684,2021-12-28,제주,7.2,5.9,8.4,0.0,0.0,9.1,360.0,5.3,...,0.91,0.0,0.0,0.0,8.3,8.0,5.6,0.9,1.3,0.0
11685,2021-12-29,제주,9.3,6.6,11.5,0.0,0.4,12.8,340.0,7.9,...,4.94,0.0,0.0,0.0,8.5,7.8,6.9,2.3,3.3,0.0
11686,2021-12-30,제주,6.9,5.8,8.4,0.0,0.0,18.1,340.0,10.1,...,4.85,0.0,0.0,0.0,8.0,8.0,5.9,2.3,3.2,0.0
11687,2021-12-31,제주,4.9,3.5,6.4,0.0,0.0,16.4,340.0,9.5,...,2.30,0.0,0.0,0.0,8.5,8.5,4.9,1.3,1.8,0.0

# 국내기후 지역별

In [3]:
df['관측지점'].unique()

array(['서울', '강릉', '춘천', '청주', '전주', '광주', '대구', '제주'], dtype=object)

In [4]:
df.columns

Index(['시간', '관측지점', '평균 기온', '최저 기온', '최고 기온', '1시간 최다강수량', '일강수량', '최대 순간풍속',
       '최대 순간 풍속 풍향', '최대 풍속', '최대 풍속 풍향', '평균 풍속', '풍정합', '최대 풍향', '평균 이슬점온도',
       '평균 상대습도', '평균 증기압', '평균 현지기압', '최고 해면 기압', '최저 해면기압', '평균 해면기압',
       '합계 일조 시간', '1시간 최다 일사량', '합계 일사', '일 최심신적설', '일 최심적설', '합계 3시간 신적설',
       '평균 전운량', '평균 중하층운량', '평균 지면온도', '합계 대형증발량', '합계 소형증발량', '안개 계속 시간'],
      dtype='object')

In [5]:
# f'{area}평균 기온', f'{area}최저 기온', f'{area}최고 기온', f'{area}1시간 최다강수량', f'{area}일강수량', f'{area}최대 순간풍속',
#       f'{area}최대 순간 풍속 풍향', f'{area}최대 풍속', f'{area}최대 풍속 풍향', f'{area}평균 풍속', f'{area}풍정합', f'{area}최대 풍향', f'{area}평균 이슬점온도',
#       f'{area}평균 상대습도', f'{area}평균 증기압', f'{area}평균 현지기압', f'{area}최고 해면 기압', f'{area}최저 해면기압', f'{area}평균 해면기압',
#       f'{area}합계 일조 시간', f'{area}1시간 최다 일사량', f'{area}합계 일사', f'{area}일 최심신적설', f'{area}일 최심적설', f'{area}합계 3시간 신적설',
#       f'{area}평균 전운량', f'{area}평균 중하층운량', f'{area}평균 지면온도', f'{area}합계 대형증발량', f'{area}합계 소형증발량', f'{area}안개 계속 시간'

In [7]:
# df['시간'].info()

In [8]:
df['시간'] = df['시간'].astype('datetime64')

In [9]:
# 옆으로 붙이기

#날짜 열 만들기
days = pd.date_range('1990-01-01','2021-12-31',freq='D')
df_c = pd.DataFrame({'시간':days})


areas = list(df['관측지점'].unique())
for area in areas:
    tmp = df[df['관측지점']== area].drop(columns='관측지점')
    tmp.columns = ['시간',f'{area}평균 기온', f'{area}최저 기온', f'{area}최고 기온', f'{area}1시간 최다강수량', f'{area}일강수량', f'{area}최대 순간풍속',
       f'{area}최대 순간 풍속 풍향', f'{area}최대 풍속', f'{area}최대 풍속 풍향', f'{area}평균 풍속', f'{area}풍정합', f'{area}최대 풍향', f'{area}평균 이슬점온도',
       f'{area}평균 상대습도', f'{area}평균 증기압', f'{area}평균 현지기압', f'{area}최고 해면 기압', f'{area}최저 해면기압', f'{area}평균 해면기압',
       f'{area}합계 일조 시간', f'{area}1시간 최다 일사량', f'{area}합계 일사', f'{area}일 최심신적설', f'{area}일 최심적설', f'{area}합계 3시간 신적설',
       f'{area}평균 전운량', f'{area}평균 중하층운량', f'{area}평균 지면온도', f'{area}합계 대형증발량', f'{area}합계 소형증발량', f'{area}안개 계속 시간']
    df_c = pd.merge(df_c,tmp, how='left', on='시간')
df_c

,시간,서울평균 기온,서울최저 기온,서울최고 기온,서울1시간 최다강수량,서울일강수량,서울최대 순간풍속,서울최대 순간 풍속 풍향,서울최대 풍속,서울최대 풍속 풍향,...,제주합계 일사,제주일 최심신적설,제주일 최심적설,제주합계 3시간 신적설,제주평균 전운량,제주평균 중하층운량,제주평균 지면온도,제주합계 대형증발량,제주합계 소형증발량,제주안개 계속 시간
0,1990-01-01,-1.7,-4.0,1.8,0.0,0.0,7.3,270.0,5.0,270.0,...,5.52,0.0,0.0,0.0,5.3,5.8,4.6,1.0,1.4,0.0
1,1990-01-02,-3.5,-5.7,-0.9,0.0,0.1,8.6,290.0,4.8,290.0,...,2.65,0.0,0.0,0.0,8.8,8.1,4.6,1.0,1.6,0.0
2,1990-01-03,-5.0,-7.2,-1.7,0.0,0.0,8.2,290.0,5.0,290.0,...,2.40,0.0,0.0,0.0,9.3,9.3,3.2,1.0,1.6,0.0
3,1990-01-04,-3.3,-8.9,2.1,0.0,0.0,6.1,290.0,3.0,290.0,...,2.89,0.0,0.0,0.0,8.0,8.4,3.5,0.8,1.1,0.0
4,1990-01-05,0.7,-2.4,2.1,0.0,3.2,12.3,290.0,7.2,290.0,...,4.64,0.0,0.0,0.0,7.5,5.8,6.5,1.0,1.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11683,2021-12-27,-7.6,-12.9,-3.9,0.0,0.0,5.5,340.0,3.1,20.0,...,1.37,0.5,1.2,0.5,8.1,8.1,3.9,1.0,1.4,0.0
11684,2021-12-28,-4.1,-8.5,-0.9,0.0,0.0,4.9,50.0,3.1,50.0,...,0.91,0.0,0.0,0.0,8.3,8.0,5.6,0.9,1.3,0.0
11685,2021-12-29,0.4,-3.8,5.9,0.0,0.2,10.8,270.0,5.9,270.0,...,4.94,0.0,0.0,0.0,8.5,7.8,6.9,2.3,3.3,0.0
11686,2021-12-30,-3.9,-6.8,0.2,0.0,0.0,12.3,320.0,6.6,290.0,...,4.85,0.0,0.0,0.0,8.0,8.0,5.9,2.3,3.2,0.0
11687,2021-12-31,-6.7,-8.8,-3.9,0.0,0.0,11.9,290.0,5.4,270.0,...,2.30,0.0,0.0,0.0,8.5,8.5,4.9,1.3,1.8,0.0

In [10]:
# 고층기후 데이터

In [16]:
df_h = pd.read_csv('./data/preprocessed_고층기후데이터.csv')
df_h.tail()

,일시,50hPa_고도,50hPa_기온,50hPa_이슬점,50hPa_풍향,50hPa_풍속,70hPa_고도,70hPa_기온,70hPa_이슬점,70hPa_풍향,...,925hPa_고도,925hPa_기온,925hPa_이슬점,925hPa_풍향,925hPa_풍속,1000hPa_고도,1000hPa_기온,1000hPa_이슬점,1000hPa_풍향,1000hPa_풍속
11683,2021-12-27,20457.5,-58.450,-89.200,270.000,37.000,18337.50,-56.250,-87.75,266.250,...,852.00,-7.50,-10.850,293.75,26.00,243.75,-6.150,-11.050,220.00,3.50
11684,2021-12-28,20442.5,-59.350,-89.850,277.500,48.250,18325.00,-57.750,-88.50,278.750,...,837.00,-3.05,-6.200,257.50,17.00,215.25,-0.850,-4.725,161.25,6.00
11685,2021-12-29,20485.0,-58.025,-89.025,241.875,30.625,18333.75,-58.000,-89.00,265.000,...,789.25,-3.45,-6.825,272.50,25.00,167.00,0.825,-4.800,266.25,14.75
11686,2021-12-30,20480.0,-59.625,-89.875,228.125,32.125,18332.50,-54.725,-86.35,273.125,...,821.25,-9.90,-17.550,312.50,21.25,213.75,-4.550,-14.550,307.50,14.00
11687,2021-12-31,20462.5,-58.700,-86.450,277.500,29.500,18350.00,-59.800,-86.80,265.000,...,856.50,-12.25,-23.750,316.25,19.25,256.25,-7.750,-21.000,313.75,11.75

In [17]:
# 전처리 

# 열이름바꾸기 
df_h.rename(columns = {'일시': '시간'}, inplace= True)
# 데이터타입
df_h['시간'] = df_h['시간'].astype('datetime64')

In [18]:
# 국내기후+ 고층기후 붙이기

df_c2 = pd.merge(df_c,df_h, how='left', on='시간')
df_c2

,시간,서울평균 기온,서울최저 기온,서울최고 기온,서울1시간 최다강수량,서울일강수량,서울최대 순간풍속,서울최대 순간 풍속 풍향,서울최대 풍속,서울최대 풍속 풍향,...,925hPa_고도,925hPa_기온,925hPa_이슬점,925hPa_풍향,925hPa_풍속,1000hPa_고도,1000hPa_기온,1000hPa_이슬점,1000hPa_풍향,1000hPa_풍속
0,1990-01-01,-1.7,-4.0,1.8,0.0,0.0,7.3,270.0,5.0,270.0,...,780.810561,8.615578,0.716938,230.239795,12.991223,183.50,-2.750,-9.500,255.00,6.25
1,1990-01-02,-3.5,-5.7,-0.9,0.0,0.1,8.6,290.0,4.8,290.0,...,780.810561,8.615578,0.716938,230.239795,12.991223,194.50,-4.650,-11.525,337.50,6.50
2,1990-01-03,-5.0,-7.2,-1.7,0.0,0.0,8.2,290.0,5.0,290.0,...,780.810561,8.615578,0.716938,230.239795,12.991223,206.00,-5.600,-13.850,150.00,7.25
3,1990-01-04,-3.3,-8.9,2.1,0.0,0.0,6.1,290.0,3.0,290.0,...,780.810561,8.615578,0.716938,230.239795,12.991223,209.75,-2.700,-12.200,228.75,6.50
4,1990-01-05,0.7,-2.4,2.1,0.0,3.2,12.3,290.0,7.2,290.0,...,780.810561,8.615578,0.716938,230.239795,12.991223,177.25,-0.850,-7.325,232.50,6.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11683,2021-12-27,-7.6,-12.9,-3.9,0.0,0.0,5.5,340.0,3.1,20.0,...,852.000000,-7.500000,-10.850000,293.750000,26.000000,243.75,-6.150,-11.050,220.00,3.50
11684,2021-12-28,-4.1,-8.5,-0.9,0.0,0.0,4.9,50.0,3.1,50.0,...,837.000000,-3.050000,-6.200000,257.500000,17.000000,215.25,-0.850,-4.725,161.25,6.00
11685,2021-12-29,0.4,-3.8,5.9,0.0,0.2,10.8,270.0,5.9,270.0,...,789.250000,-3.450000,-6.825000,272.500000,25.000000,167.00,0.825,-4.800,266.25,14.75
11686,2021-12-30,-3.9,-6.8,0.2,0.0,0.0,12.3,320.0,6.6,290.0,...,821.250000,-9.900000,-17.550000,312.500000,21.250000,213.75,-4.550,-14.550,307.50,14.00
11687,2021-12-31,-6.7,-8.8,-3.9,0.0,0.0,11.9,290.0,5.4,270.0,...,856.500000,-12.250000,-23.750000,316.250000,19.250000,256.25,-7.750,-21.000,313.75,11.75

In [19]:
df_c2.columns.to_list()

['시간',
 '서울평균 기온',
 '서울최저 기온',
 '서울최고 기온',
 '서울1시간 최다강수량',
 '서울일강수량',
 '서울최대 순간풍속',
 '서울최대 순간 풍속 풍향',
 '서울최대 풍속',
 '서울최대 풍속 풍향',
 '서울평균 풍속',
 '서울풍정합',
 '서울최대 풍향',
 '서울평균 이슬점온도',
 '서울평균 상대습도',
 '서울평균 증기압',
 '서울평균 현지기압',
 '서울최고 해면 기압',
 '서울최저 해면기압',
 '서울평균 해면기압',
 '서울합계 일조 시간',
 '서울1시간 최다 일사량',
 '서울합계 일사',
 '서울일 최심신적설',
 '서울일 최심적설',
 '서울합계 3시간 신적설',
 '서울평균 전운량',
 '서울평균 중하층운량',
 '서울평균 지면온도',
 '서울합계 대형증발량',
 '서울합계 소형증발량',
 '서울안개 계속 시간',
 '강릉평균 기온',
 '강릉최저 기온',
 '강릉최고 기온',
 '강릉1시간 최다강수량',
 '강릉일강수량',
 '강릉최대 순간풍속',
 '강릉최대 순간 풍속 풍향',
 '강릉최대 풍속',
 '강릉최대 풍속 풍향',
 '강릉평균 풍속',
 '강릉풍정합',
 '강릉최대 풍향',
 '강릉평균 이슬점온도',
 '강릉평균 상대습도',
 '강릉평균 증기압',
 '강릉평균 현지기압',
 '강릉최고 해면 기압',
 '강릉최저 해면기압',
 '강릉평균 해면기압',
 '강릉합계 일조 시간',
 '강릉1시간 최다 일사량',
 '강릉합계 일사',
 '강릉일 최심신적설',
 '강릉일 최심적설',
 '강릉합계 3시간 신적설',
 '강릉평균 전운량',
 '강릉평균 중하층운량',
 '강릉평균 지면온도',
 '강릉합계 대형증발량',
 '강릉합계 소형증발량',
 '강릉안개 계속 시간',
 '춘천평균 기온',
 '춘천최저 기온',
 '춘천최고 기온',
 '춘천1시간 최다강수량',
 '춘천일강수량',
 '춘천최대 순간풍속',
 '춘천최대 순간 풍속 풍향',
 '춘천최대 풍속',
 '춘천최대 풍속 풍향',
 '춘천평균 풍속',
 '춘천풍정합',
 '춘천최대 풍향',
 '춘천평균 이슬점온도',
 '춘천평균 상대습도',
 '춘천평균 증기압',
 '춘천평균 현지기압',
 '춘천최고 해면 기압',
 '춘천최저 해면기압',
 '춘천평균 해면기압',
 '춘천합계 일조 시간',
 '춘천1시간 최다 일사량',
 '춘천합계 일사',
 '춘천일 최심신적설',
 '춘천일 최심적설',
 '춘천합계 3시간 신적설',
 '춘천평균 전운량',
 '춘천평균 중하층운량',
 '춘천평균 지면온도',
 '춘천합계 대형증발량',
 '춘천합계 소형증발량',
 '춘천안개 계속 시간',
 '청주평균 기온',
 '청주최저 기온',
 '청주최고 기온',
 '청주1시간 최다강수량',
 '청주일강수량',
 '청주최대 순간풍속',
 '청주최대 순간 풍속 풍향',
 '청주최대 풍속',
 '청주최대 풍속 풍향',
 '청주평균 풍속',
 '청주풍정합',
 '청주최대 풍향',
 '청주평균 이슬점온도',
 '청주평균 상대습도',
 '청주평균 증기압',
 '청주평균 현지기압',
 '청주최고 해면 기압',
 '청주최저 해면기압',
 '청주평균 해면기압',
 '청주합계 일조 시간',
 '청주1시간 최다 일사량',
 '청주합계 일사',
 '청주일 최심신적설',
 '청주일 최심적설',
 '청주합계 3시간 신적설',
 '청주평균 전운량',
 '청주평균 중하층운량',
 '청주평균 지면온도',
 '청주합계 대형증발량',
 '청주합계 소형증발량',
 '청주안개 계속 시간',
 '전주평균 기온',
 '전주최저 기온',
 '전주최고 기온',
 '전주1시간 최다강수량',
 '전주일강수량',
 '전주최대 순간풍속',
 '전주최대 순간 풍속 풍향',
 '전주최대 풍속',
 '전주최대 풍속 풍향',
 '전주평균 풍속',
 '전주풍정합',
 '전주최대 풍향',
 '전주평균 이슬점온도',
 '전주평균 상대습도',
 '전주평균 증기압',
 '전주평균 현지기압',
 '전주최고 해면 기압',
 '전주최저 해면기압',
 '전주평균 해면기압',
 '전주합계 일조 시간',
 '전주1시간 최다 일사량',
 '전주합계 일사',
 '전주일 최심신적설',
 '전주일 최심적설',
 '전주합계 3시간 신적설',
 '전주평균 전운량',
 '전주평균 중하층운량',
 '전주평균 지면온도',
 '전주합계 대형증발량',
 '전주합계 소형증발량',
 '전주안개 계속 시간',
 '광주평균 기온',
 '광주최저 기온',
 '광주최고 기온',
 '광주1시간 최다강수량',
 '광주일강수량',
 '광주최대 순간풍속',
 '광주최대 순간 풍속 풍향',
 '광주최대 풍속',
 '광주최대 풍속 풍향',
 '광주평균 풍속',
 '광주풍정합',
 '광주최대 풍향',
 '광주평균 이슬점온도',
 '광주평균 상대습도',
 '광주평균 증기압',
 '광주평균 현지기압',
 '광주최고 해면 기압',
 '광주최저 해면기압',
 '광주평균 해면기압',
 '광주합계 일조 시간',
 '광주1시간 최다 일사량',
 '광주합계 일사',
 '광주일 최심신적설',
 '광주일 최심적설',
 '광주합계 3시간 신적설',
 '광주평균 전운량',
 '광주평균 중하층운량',
 '광주평균 지면온도',
 '광주합계 대형증발량',
 '광주합계 소형증발량',
 '광주안개 계속 시간',
 '대구평균 기온',
 '대구최저 기온',
 '대구최고 기온',
 '대구1시간 최다강수량',
 '대구일강수량',
 '대구최대 순간풍속',
 '대구최대 순간 풍속 풍향',
 '대구최대 풍속',
 '대구최대 풍속 풍향',
 '대구평균 풍속',
 '대구풍정합',
 '대구최대 풍향',
 '대구평균 이슬점온도',
 '대구평균 상대습도',
 '대구평균 증기압',
 '대구평균 현지기압',
 '대구최고 해면 기압',
 '대구최저 해면기압',
 '대구평균 해면기압',
 '대구합계 일조 시간',
 '대구1시간 최다 일사량',
 '대구합계 일사',
 '대구일 최심신적설',
 '대구일 최심적설',
 '대구합계 3시간 신적설',
 '대구평균 전운량',
 '대구평균 중하층운량',
 '대구평균 지면온도',
 '대구합계 대형증발량',
 '대구합계 소형증발량',
 '대구안개 계속 시간',
 '제주평균 기온',
 '제주최저 기온',
 '제주최고 기온',
 '제주1시간 최다강수량',
 '제주일강수량',
 '제주최대 순간풍속',
 '제주최대 순간 풍속 풍향',
 '제주최대 풍속',
 '제주최대 풍속 풍향',
 '제주평균 풍속',
 '제주풍정합',
 '제주최대 풍향',
 '제주평균 이슬점온도',
 '제주평균 상대습도',
 '제주평균 증기압',
 '제주평균 현지기압',
 '제주최고 해면 기압',
 '제주최저 해면기압',
 '제주평균 해면기압',
 '제주합계 일조 시간',
 '제주1시간 최다 일사량',
 '제주합계 일사',
 '제주일 최심신적설',
 '제주일 최심적설',
 '제주합계 3시간 신적설',
 '제주평균 전운량',
 '제주평균 중하층운량',
 '제주평균 지면온도',
 '제주합계 대형증발량',
 '제주합계 소형증발량',
 '제주안개 계속 시간',
 '50hPa_고도',
 '50hPa_기온',
 '50hPa_이슬점',
 '50hPa_풍향',
 '50hPa_풍속',
 '70hPa_고도',
 '70hPa_기온',
 '70hPa_이슬점',
 '70hPa_풍향',
 '70hPa_풍속',
 '100hPa_고도',
 '100hPa_기온',
 '100hPa_이슬점',
 '100hPa_풍향',
 '100hPa_풍속',
 '150hPa_고도',
 '150hPa_기온',
 '150hPa_이슬점',
 '150hPa_풍향',
 '150hPa_풍속',
 '200hPa_고도',
 '200hPa_기온',
 '200hPa_이슬점',
 '200hPa_풍향',
 '200hPa_풍속',
 '250hPa_고도',
 '250hPa_기온',
 '250hPa_이슬점',
 '250hPa_풍향',
 '250hPa_풍속',
 '300hPa_고도',
 '300hPa_기온',
 '300hPa_이슬점',
 '300hPa_풍향',
 '300hPa_풍속',
 '400hPa_고도',
 '400hPa_기온',
 '400hPa_이슬점',
 '400hPa_풍향',
 '400hPa_풍속',
 '500hPa_고도',
 '500hPa_기온',
 '500hPa_이슬점',
 '500hPa_풍향',
 '500hPa_풍속',
 '700hPa_고도',
 '700hPa_기온',
 '700hPa_이슬점',
 '700hPa_풍향',
 '700hPa_풍속',
 '850hPa_고도',
 '850hPa_기온',
 '850hPa_이슬점',
 '850hPa_풍향',
 '850hPa_풍속',
 '925hPa_고도',
 '925hPa_기온',
 '925hPa_이슬점',
 '925hPa_풍향',
 '925hPa_풍속',
 '1000hPa_고도',
 '1000hPa_기온',
 '1000hPa_이슬점',
 '1000hPa_풍향',
 '1000hPa_풍속']

In [20]:
# df_c2.to_csv('./data/국내+고층.csv')

# 주변국 기후

In [21]:
df_w = pd.read_csv('./data/preprocessed_주변국 기상데이터_중국 부분 제거.csv',index_col=0)
df_w.tail()

,도시명,일시,평균기온,최고기온,최저기온,습도,풍향,풍속,강수량,해면기압,이슬점 온도,군집
9492,후쿠오카,2021-12-27,4.241667,5.7,2.7,57.520833,70.0,5.166667,-6.200369,1029.083333,-3.525000,n5
9493,후쿠오카,2021-12-28,6.725000,9.1,3.6,64.204167,340.0,3.625000,-6.200369,1026.175000,0.316667,n5
9494,후쿠오카,2021-12-29,8.708333,10.4,5.6,69.545833,50.0,5.375000,2.000000,1019.891667,3.175000,n5
9495,후쿠오카,2021-12-30,6.966667,9.7,4.3,50.762500,300.0,9.875000,-6.200369,1023.591667,-2.570833,n5
9496,후쿠오카,2021-12-31,4.200000,4.2,4.2,43.900000,320.0,5.428593,0.000000,1028.500000,-7.000000,n5

In [22]:
df_w['군집'].unique()

array(['n2', 'n1', 'n5', 'n7', 'n6', 'n4', 'n3'], dtype=object)

In [23]:
df_w[df_w['군집']== 'n1']['도시명'].unique()

array(['신의주', '원산', '평양', '남포', '사리원', '용연', '해주', '개성'], dtype=object)

In [24]:
df_w[df_w['군집']== 'n2']['도시명'].unique()

array(['청진', '혜산', '강계', '함흥'], dtype=object)

In [25]:
df_w[df_w['군집']== 'n3']['도시명'].unique()

array(['블라디보스톡'], dtype=object)

In [26]:
df_w[df_w['군집']== 'n4']['도시명'].unique()

array(['도쿄', '삿포로', '센다이'], dtype=object)

In [27]:
df_w[df_w['군집']== 'n5']['도시명'].unique()

array(['가고시마', '나고야', '다카마쓰', '오사카', '후쿠오카'], dtype=object)

In [28]:
df_w[df_w['군집']== 'n6']['도시명'].unique()

array(['다롄', '베이징', '선양', '창춘', '텐진'], dtype=object)

In [29]:
df_w[df_w['군집']== 'n7']['도시명'].unique()

array(['난징', '상하이', '지난'], dtype=object)

In [30]:
df_w.rename(columns = {'일시': '시간'},inplace=True)

In [33]:
df_w['시간'] =df_w['시간'].astype('datetime64')

In [34]:
#사용할 도시

# cities = ['신의주','평양','청진', '혜산', '강계', '함흥','블라디보스톡','도쿄', '삿포로', '센다이','가고시마','오사카', '후쿠오카','베이징', '선양', '창춘','상하이', '지난']

In [35]:
df_w.columns

Index(['도시명', '시간', '평균기온', '최고기온', '최저기온', '습도', '풍향', '풍속', '강수량', '해면기압',
       '이슬점 온도', '군집'],
      dtype='object')

In [36]:
#사용할 도시

cities = ['신의주','평양','청진', '혜산', '강계', '함흥','블라디보스톡','도쿄', '삿포로', '센다이','가고시마','오사카', '후쿠오카','베이징', '선양', '창춘','상하이', '지난']


# 합치기(1996년 )
days = pd.date_range('1996-01-01','2021-12-31',freq='D')
df_c3 = pd.DataFrame({'시간':days})

for city in cities:
    tmp = df_w[df_w['도시명']== city].drop(columns=['도시명','군집'])
    tmp.columns = ['시간',f'{city}평균기온', f'{city}최고기온', f'{city}최저기온', f'{city}습도',f'{city}풍향', f'{city}풍속',
                   f'{city}강수량', f'{city}해면기압',f'{city}이슬점 온도']
    df_c3 = pd.merge(df_c3,tmp, how='left', on='시간')

df_c3

,시간,신의주평균기온,신의주최고기온,신의주최저기온,신의주습도,신의주풍향,신의주풍속,신의주강수량,신의주해면기압,신의주이슬점 온도,...,상하이이슬점 온도,지난평균기온,지난최고기온,지난최저기온,지난습도,지난풍향,지난풍속,지난강수량,지난해면기압,지난이슬점 온도
0,1996-01-01,-6.757143,-2.5,-10.9,63.000000,340.0,0.428571,0.000000,1023.066667,-13.042857,...,2.7000,9.466667,10.4,8.2,28.6000,10.0,4.666667,0.0,1014.266667,-7.866667
1,1996-01-02,-0.362500,2.7,-3.3,66.750000,0.0,1.500000,0.000000,1015.737500,-6.162500,...,-0.2625,2.550000,9.6,-3.9,30.0750,40.0,4.625000,0.0,1025.587500,-14.050000
2,1996-01-03,-8.400000,-6.7,-10.6,39.857143,0.0,4.250000,0.000000,1023.412500,-17.350000,...,-1.0625,-1.712500,1.0,-4.3,37.0375,60.0,2.125000,0.0,1028.212500,-14.887500
3,1996-01-04,-9.450000,-4.4,-14.3,71.000000,60.0,0.750000,3.597862,1024.375000,-13.900000,...,3.3125,1.362500,5.3,-2.4,54.5000,30.0,1.500000,0.0,1018.650000,-7.100000
4,1996-01-05,-1.700000,3.2,-4.1,67.375000,350.0,1.250000,0.000000,1021.350000,-7.062500,...,5.6250,0.650000,5.2,-2.7,69.2000,40.0,2.500000,0.0,1024.350000,-4.725000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9492,2021-12-27,-10.025000,-4.8,-14.6,53.875000,90.0,1.250000,0.000000,1031.400000,-18.050000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9493,2021-12-28,-6.675000,-1.1,-11.4,63.375000,30.0,1.375000,0.000000,1027.200000,-12.662500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9494,2021-12-29,-4.137500,-1.0,-6.8,54.875000,50.0,2.625000,0.000000,1020.737500,-12.850000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9495,2021-12-30,-7.712500,-3.2,-11.7,41.125000,60.0,2.375000,0.000000,1027.200000,-19.100000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9496,2021-12-31,-7.937500,-3.4,-11.0,34.500000,300.0,1.125000,0.000000,1033.687500,-21.200000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 국내기후+ 고층기후 + 주변국기후(1996년~ 2021년 8월)

In [37]:
df_c4 = pd.merge(df_c2, df_c3, how='left', on= '시간')

In [38]:
df_c4.set_index('시간', inplace=True)

In [39]:
df_c4

,서울평균 기온,서울최저 기온,서울최고 기온,서울1시간 최다강수량,서울일강수량,서울최대 순간풍속,서울최대 순간 풍속 풍향,서울최대 풍속,서울최대 풍속 풍향,서울평균 풍속,...,상하이이슬점 온도,지난평균기온,지난최고기온,지난최저기온,지난습도,지난풍향,지난풍속,지난강수량,지난해면기압,지난이슬점 온도
시간,,,,,,,,,,,,,,,,,,,,,
1990-01-01,-1.7,-4.0,1.8,0.0,0.0,7.3,270.0,5.0,270.0,1.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-02,-3.5,-5.7,-0.9,0.0,0.1,8.6,290.0,4.8,290.0,2.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-03,-5.0,-7.2,-1.7,0.0,0.0,8.2,290.0,5.0,290.0,2.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-04,-3.3,-8.9,2.1,0.0,0.0,6.1,290.0,3.0,290.0,1.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-05,0.7,-2.4,2.1,0.0,3.2,12.3,290.0,7.2,290.0,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-27,-7.6,-12.9,-3.9,0.0,0.0,5.5,340.0,3.1,20.0,1.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-28,-4.1,-8.5,-0.9,0.0,0.0,4.9,50.0,3.1,50.0,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-29,0.4,-3.8,5.9,0.0,0.2,10.8,270.0,5.9,270.0,2.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-30,-3.9,-6.8,0.2,0.0,0.0,12.3,320.0,6.6,290.0,3.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-31,-6.7,-8.8,-3.9,0.0,0.0,11.9,290.0,5.4,270.0,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
df_c5 = df_c4.loc['1996-01-01':'2021-08-31']
df_c5

,서울평균 기온,서울최저 기온,서울최고 기온,서울1시간 최다강수량,서울일강수량,서울최대 순간풍속,서울최대 순간 풍속 풍향,서울최대 풍속,서울최대 풍속 풍향,서울평균 풍속,...,상하이이슬점 온도,지난평균기온,지난최고기온,지난최저기온,지난습도,지난풍향,지난풍속,지난강수량,지난해면기압,지난이슬점 온도
시간,,,,,,,,,,,,,,,,,,,,,
1996-01-01,-3.2,-7.9,2.5,0.0,0.0,6.0,340.0,3.5,290.0,1.6,...,2.700000,9.466667,10.4,8.2,28.6000,10.0,4.666667,0.00000,1014.266667,-7.866667
1996-01-02,0.2,-3.9,3.9,0.0,0.0,9.3,230.0,3.8,230.0,1.8,...,-0.262500,2.550000,9.6,-3.9,30.0750,40.0,4.625000,0.00000,1025.587500,-14.050000
1996-01-03,-4.5,-8.5,5.5,0.0,0.0,17.5,270.0,8.2,290.0,5.3,...,-1.062500,-1.712500,1.0,-4.3,37.0375,60.0,2.125000,0.00000,1028.212500,-14.887500
1996-01-04,-5.4,-10.7,-0.1,0.0,0.0,7.1,270.0,3.5,270.0,1.2,...,3.312500,1.362500,5.3,-2.4,54.5000,30.0,1.500000,0.00000,1018.650000,-7.100000
1996-01-05,-0.1,-2.1,2.0,0.0,2.0,7.8,70.0,3.7,70.0,2.4,...,5.625000,0.650000,5.2,-2.7,69.2000,40.0,2.500000,0.00000,1024.350000,-4.725000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-27,22.4,20.4,25.5,0.7,0.9,4.9,250.0,3.2,250.0,1.3,...,26.737500,22.200000,26.1,17.8,68.6500,350.0,2.250000,0.00000,1013.300000,15.925000
2021-08-28,23.6,19.7,28.2,0.0,0.0,7.3,270.0,3.9,270.0,1.8,...,26.957143,23.200000,28.4,18.9,75.6250,320.0,1.500000,-2.07536,1013.387500,18.337500
2021-08-29,23.7,21.9,26.3,0.7,0.9,5.6,340.0,3.4,320.0,1.6,...,26.700000,20.550000,21.9,18.8,92.9875,50.0,0.875000,-2.07536,1014.112500,19.362500
2021-08-30,24.2,21.2,27.7,0.0,0.0,4.5,270.0,2.9,250.0,1.4,...,25.887500,22.400000,24.3,21.4,93.1250,40.0,1.500000,-2.07536,1013.275000,21.212500
2021-08-31,20.5,18.1,23.1,12.4,77.4,9.3,70.0,4.9,70.0,2.3,...,25.287500,19.912500,21.7,18.8,94.7875,50.0,2.625000,-2.07536,1012.675000,19.050000

In [41]:
df_c5.to_csv('./data/국내+고층+주변국.csv')