In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import math

In [2]:
def wind_direct(s):
    if s.value_counts().head(1).index == 99:
        return 99
    else:
        return s[s.values != 99].mean()

In [20]:
# 파일 목록 연도
year = []
for i in range(1996,2022):
    year.append(i)
    
# year

In [ ]:
# n1 = 북한 남쪽
# n2 = 북한 북쪽
# n3 = 블라디보스톡
# n4 = 일본 동쪽
# n5 = 일본 서쪽
# n6 = 중국 북쪽
# n7 = 중국 남쪽

In [35]:
cities = pd.DataFrame()

for y in year:

    # 파일불러오기
    df = pd.read_csv('./러일중 1996~현재 기후(시간단위)/러일중 {}(시간).csv'.format(y), encoding='euckr')
    df_n = pd.read_csv('./북한 기후 시간단위/북한 {}(시간).csv'.format(y), encoding='euckr')

    # 변화량기압 drop
    df.drop('변화량 기압', axis=1, inplace=True)
    idx_r = df[df['지점명']=='상페테르부르크'].index
    df = df.drop(idx_r)
    idx_r = df[df['지점명']=='모스코바'].index
    df = df.drop(idx_r)

    # 북한 rename해주기
    df_n.rename(columns={'지점':'지점명'}, inplace=True)
    df_n.rename(columns={'풍향(36방위)':'풍향'}, inplace=True)


    # 일시 시간 버리기
    df['일시'] = df['일시'].apply(lambda x:x.split()[0])
    df_n['일시'] = df_n['일시'].apply(lambda x:x.split()[0])

    # 풍향 nan값 99로 바꾸기
    df['16 방위 풍향'].fillna(99,inplace=True)
    df['16 방위 풍향'] = df['16 방위 풍향'].apply(lambda x : 99 if x > 36 else x)

    df_n['풍향'].fillna(99,inplace=True)
    df_n['풍향'] = df_n['풍향'].apply(lambda x : 99 if x > 36 else x)

    # 방향마다 풍향 계산
    df['x_axis'] = df['16 방위 풍향'].apply(lambda x: math.sin(math.radians(x*10)) if 0<x<37 else x)
    df['y_axis'] = df['16 방위 풍향'].apply(lambda x: math.cos(math.radians(x*10)) if 0<x<37 else x)

    df_n['x_axis_n'] = df_n['풍향'].apply(lambda x: math.sin(math.radians(x*10)) if 0<x<37 else x)
    df_n['y_axis_n'] = df_n['풍향'].apply(lambda x: math.cos(math.radians(x*10)) if 0<x<37 else x)

    # 풍향 데이터프레임 만들기
    tdf = df.groupby(['지점명','일시'])['x_axis', 'y_axis'].agg(wind_direct).reset_index()
    tdf_n = df_n.groupby(['지점명','일시'])['x_axis_n', 'y_axis_n'].agg(wind_direct).reset_index()

    # 일일 풍향 만들기
    tmplst = []
    for ind in range(len(tdf)):
        if tdf.loc[ind,'x_axis'] == 99:
            tmplst.append(1000)
        else:
            tmplst.append(math.degrees(math.atan(tdf.loc[ind,'x_axis']/tdf.loc[ind,'y_axis'])))
    tdf['일일 풍향']=tmplst

    tmplst_n = []
    for ind_n in range(len(tdf_n)):
        if tdf_n.loc[ind_n,'x_axis_n'] == 99:
            tmplst_n.append(1000)
        else:
            tmplst_n.append(math.degrees(math.atan(tdf_n.loc[ind_n,'x_axis_n']/tdf_n.loc[ind_n,'y_axis_n'])))
    tdf_n['일일 풍향']=tmplst_n

    # 풍향이 기입이 안된곳에 0으로 채우기
    tdf['일일 풍향'] = tdf['일일 풍향'].apply(lambda x: round(x+360,ndigits=-1) if x<0 else round(x,ndigits=-1)).fillna(0)
    tdf_n['일일 풍향'] = tdf_n['일일 풍향'].apply(lambda x: round(x+360,ndigits=-1) if x<0 else round(x,ndigits=-1)).fillna(0)

    # 풍향을 제외한 내용들 일일로 묶어주기
    df_tt = df.groupby(['지점명', '일시']).agg({'기온':['mean','max','min'], '습도':'mean', 
                                            '풍속':'mean', '강수량':'sum','해면기압':'mean', '이슬점 온도':'mean'})

    df_tt.columns = ['평균기온','최고기온','최저기온','습도','풍속','강수량','해면기압','이슬점 온도']
    df_city = df_tt.reset_index()

    df_tt_n = df_n.groupby(['지점명', '일시']).agg({'기온(°C)':['mean','max','min'], '상대습도(%)':'mean', 
                                            '풍속(m/s)':'mean', '12시간강수량(mm)':'sum','해면기압(hPa)':'mean',
                                            '이슬점온도(°C)':'mean'})

    df_tt_n.columns = ['평균기온','최고기온','최저기온','습도','풍속','강수량','해면기압','이슬점 온도']
    df_city_n = df_tt_n.reset_index()

    # 풍향데이터와 나머지 데이터 concat
    df_city = pd.concat([df_city,tdf['일일 풍향']],axis=1)
    df_city_n = pd.concat([df_city_n,tdf_n['일일 풍향']],axis=1)


    # 컬럼이름 순서 바꾸기
    df_city = df_city[['지점명', '일시', '평균기온', '최고기온', '최저기온', '습도', '일일 풍향','풍속',  '강수량', '해면기압', 
           '이슬점 온도']]
    df_city.rename({'일일 풍향':'풍향'},axis = 1,inplace=True)

    df_city_n = df_city_n[['지점명', '일시', '평균기온', '최고기온', '최저기온', '습도', '일일 풍향','풍속',  '강수량', '해면기압',
           '이슬점 온도']]
    df_city_n.rename({'일일 풍향':'풍향'},axis = 1,inplace=True)

    # 군집번호 정하기
    j_li = ['도쿄','오사카','나고야','삿포로','센다이','니가타','히로시마','다카마쓰','후쿠오카','가고시마','오키나와',
            '난징','베이징','상하이','선양','창춘','텐진','다롄','지난','블라디보스톡']
    j_li_n = ['n4','n5','n5','n4','n4','n4','n5','n5','n5','n5','n5','n7','n6','n7','n6','n6','n6','n6','n7','n3']

    no = [5, 22, 16, 20, 14, 39, 46, 31, 41, 25, 3, 8]
    li_c=[]
    for i in df_city_n['지점명']:
        if i in no:
            li_c.append('n2')
        else:
            li_c.append('n1')

    # 군집번호 넣어주기
    df_city['군집'] = df_city['지점명'].apply(lambda x : j_li_n[j_li.index(x)] if x in j_li else np.nan)
    city = df_city[df_city['군집'].isna()==False]

    df_city_n['군집'] = li_c



    # 러일중 + 북한
    city_sum = pd.concat([df_city_n,city])
    
    # 연도별 모두 합치기
    cities = pd.concat([cities, city_sum])

# 인덱스 reset
cities = cities.reset_index()

# 파일 저장
cities.to_csv('주변국_기후.csv')

In [73]:
df_w = pd.read_csv('./주변국_기후.csv', index_col=0)
# df_w.drop('index', axis=1, inplace=True)
df_w.head()

,지점명,일시,평균기온,최고기온,최저기온,습도,풍향,풍속,강수량,해면기압,이슬점 온도,군집
0,3,1996-01-01,-6.542857,-1.5,-9.8,47.000,330.0,2.571429,0.0,1018.785714,-16.4000,n2
1,3,1996-01-02,-4.687500,1.5,-10.4,75.500,360.0,0.500000,0.0,1014.662500,-8.6250,n2
2,3,1996-01-03,-7.400000,-1.1,-11.6,57.625,320.0,8.250000,0.0,1010.962500,-14.6000,n2
3,3,1996-01-04,-8.862500,-5.0,-12.0,48.375,330.0,2.375000,0.0,1020.400000,-18.2375,n2
4,3,1996-01-05,-6.300000,-0.8,-10.5,79.625,20.0,0.500000,0.0,1021.712500,-9.4250,n2

In [78]:
# 북한 도시명 바꿔주기

north = ['평양', '해주', '원산', '함흥', '강계', '신의주', '청진', 
            '혜산', '남포', '사리원', '개성', '용연', '안주', '삼지연', '선봉', '신포', '수풍','양덕', '신계', '풍산', '구성',
          '장전','희천','김책','평강','장진','중강']


north_n = ['58', '69', '55', '41', '20', '35', '8', '16', '60', '65', '70', '68', '50', '5', '3', '46', '28', '52', '67', '22', '37', '61', '39', '25', '75', '31', '14']


df_w['지점명'] = df_w['지점명'].apply(lambda x : north[north_n.index(x)] if x in north_n else x)



df_w.rename({'지점명':'도시명'},axis = 1,inplace=True)

df_w.to_csv('주변국_기후_도시명.csv')

df_w

,도시명,일시,평균기온,최고기온,최저기온,습도,풍향,풍속,강수량,해면기압,이슬점 온도,군집
0,선봉,1996-01-01,-6.542857,-1.5,-9.8,47.000000,330.0,2.571429,0.0,1018.785714,-16.400000,n2
1,선봉,1996-01-02,-4.687500,1.5,-10.4,75.500000,360.0,0.500000,0.0,1014.662500,-8.625000,n2
2,선봉,1996-01-03,-7.400000,-1.1,-11.6,57.625000,320.0,8.250000,0.0,1010.962500,-14.600000,n2
3,선봉,1996-01-04,-8.862500,-5.0,-12.0,48.375000,330.0,2.375000,0.0,1020.400000,-18.237500,n2
4,선봉,1996-01-05,-6.300000,-0.8,-10.5,79.625000,20.0,0.500000,0.0,1021.712500,-9.425000,n2
...,...,...,...,...,...,...,...,...,...,...,...,...
420345,히로시마,2021-12-27,3.295833,5.3,0.6,60.487500,320.0,4.500000,0.5,1026.608333,-3.920833,n5
420346,히로시마,2021-12-28,5.887500,9.5,3.2,62.079167,350.0,4.416667,-99.8,1026.020833,-1.250000,n5
420347,히로시마,2021-12-29,7.162500,9.2,4.3,72.129167,80.0,4.583333,-98.8,1018.200000,2.329167,n5
420348,히로시마,2021-12-30,4.291667,8.8,0.4,59.554167,280.0,6.625000,-97.8,1020.458333,-3.316667,n5
420349,히로시마,2021-12-31,1.300000,1.3,1.3,75.200000,10.0,3.000000,2.0,1024.100000,-2.600000,n5

In [110]:
# 평온, 고온, 저온, 이슬점 - 보간
# 습도, 풍속, 해면기압 - 지역평균

df_w['평균기온'].interpolate(inplace=True)

df_w['평균기온'].isna().sum()

# 평온, 고온, 저온, 이슬점 - 보간 채우기

df_w['최고기온'].interpolate(inplace=True)
df_w['최저기온'].interpolate(inplace=True)
df_w['이슬점 온도'].interpolate(inplace=True)

# 습도, 풍속, 해면기압 - 지역평균 값 채우기

columns = ['습도', '풍속', '해면기압']
for col in columns:
    df[col] = np.where( pd.notnull(df[col]) == True, df[col], df.groupby('도시명')[col].transform(np.mean))
    
df_w.drop('nan', axis=1, inplace=True)

df_w.to_csv('주변국_기후_도시명.csv')

0

In [143]:
df_dd = pd.read_csv('./주변국_기후_도시명.csv', index_col=0)
df_dd

,도시명,일시,평균기온,최고기온,최저기온,습도,풍향,풍속,강수량,해면기압,이슬점 온도,군집
0,선봉,1996-01-01,-6.542857,-1.5,-9.8,47.000000,330.0,47.000000,0.0,47.000000,-16.400000,n2
1,선봉,1996-01-02,-4.687500,1.5,-10.4,75.500000,360.0,75.500000,0.0,75.500000,-8.625000,n2
2,선봉,1996-01-03,-7.400000,-1.1,-11.6,57.625000,320.0,57.625000,0.0,57.625000,-14.600000,n2
3,선봉,1996-01-04,-8.862500,-5.0,-12.0,48.375000,330.0,48.375000,0.0,48.375000,-18.237500,n2
4,선봉,1996-01-05,-6.300000,-0.8,-10.5,79.625000,20.0,79.625000,0.0,79.625000,-9.425000,n2
...,...,...,...,...,...,...,...,...,...,...,...,...
420345,히로시마,2021-12-27,3.295833,5.3,0.6,60.487500,320.0,60.487500,0.5,60.487500,-3.920833,n5
420346,히로시마,2021-12-28,5.887500,9.5,3.2,62.079167,350.0,62.079167,-99.8,62.079167,-1.250000,n5
420347,히로시마,2021-12-29,7.162500,9.2,4.3,72.129167,80.0,72.129167,-98.8,72.129167,2.329167,n5
420348,히로시마,2021-12-30,4.291667,8.8,0.4,59.554167,280.0,59.554167,-97.8,59.554167,-3.316667,n5
420349,히로시마,2021-12-31,1.300000,1.3,1.3,75.200000,10.0,75.200000,2.0,75.200000,-2.600000,n5